=== Ajuan08/LMSGI_UD4/Modulos CFGS/modulos.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT modulos (programacion,LenguajeMarcas)>
<!ATTLIST modulos
  xmlns CDATA #FIXED ''>

<!ELEMENT programacion (Clase1)>
<!ATTLIST programacion
  xmlns CDATA #FIXED ''>

<!ELEMENT LenguajeMarcas (Clase1)>
<!ATTLIST LenguajeMarcas
  xmlns CDATA #FIXED ''>

<!ELEMENT Clase1 (Contenidos)>
<!ATTLIST Clase1
  xmlns CDATA #FIXED ''>

<!ELEMENT Contenidos (Tema1,Tema2,Tema3)>
<!ATTLIST Contenidos
  xmlns CDATA #FIXED ''>

<!ELEMENT Tema1 (lenguaje,tipo,duracion,descripcion)>
<!ATTLIST Tema1
  xmlns CDATA #FIXED ''>

<!ELEMENT Tema2 (lenguaje,tipo,duracion,descripcion)>
<!ATTLIST Tema2
  xmlns CDATA #FIXED ''>

<!ELEMENT Tema3 (lenguaje,tipo,duracion,descripcion)>
<!ATTLIST Tema3
  xmlns CDATA #FIXED ''>

<!ELEMENT lenguaje (#PCDATA)>
<!ATTLIST lenguaje
  xmlns CDATA #FIXED ''>

<!ELEMENT tipo EMPTY>
<!ATTLIST tipo
  xmlns CDATA #FIXED ''>

<!ELEMENT duracion (#PCDATA)>
<!ATTLIST duracion
  xmlns CDATA #FIXED ''>

<!ELEMENT descripcion (#PCDATA)>
<!ATTLIST descripcion
  xmlns CDATA #FIXED ''>

=== Ajuan08/LMSGI_UD4/Modulos CFGS/modulos.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE modulos SYSTEM "modulos.dtd">
<modulos>
    <programacion>
        <Clase1>
            <Contenidos>
                <Tema1>
                    <lenguaje>JAVA</lenguaje>
                    <tipo>Practico</tipo>
                    <duracion>3 meses</duracion>
                    <descripcion>Dificultad alta</descripcion>
                </Tema1>
                <Tema2>
                    <lenguaje>PHYTON</lenguaje>
                    <tipo>Practico</tipo>
                    <duracion>2 meses</duracion>
                    <descripcion>Dificultad facil</descripcion>
                </Tema2>
                <Tema3>
                    <lenguaje>C++</lenguaje>
                    <tipo>Practico</tipo>
                    <duracion>4 meses</duracion>
                    <descripcion>Dificultad media</descripcion>
                </Tema3>
            </Contenidos>
        </Clase1>
    </programacion>
    <LenguajeMarcas>
        <Clase1>
            <Contenidos>
                <Tema1>
                    <lenguaje>XML</lenguaje>
                    <tipo>Practico</tipo>
                    <duracion>2 meses</duracion>
                    <descripcion>Dificultad media</descripcion>
                </Tema1>
                <Tema2>
                    <lenguaje>HTML</lenguaje>
                    <tipo>Teorico</tipo>
                    <duracion>4 meses</duracion>
                    <descripcion>Dificultad facil</descripcion>
                </Tema2>
                <Tema3>
                    <lenguaje>CSS</lenguaje>
                    <tipo>Teorico</tipo>
                    <duracion>3 meses</duracion>
                    <descripcion>Dificultad media</descripcion>
                </Tema3>
            </Contenidos>
        </Clase1>
    </LenguajeMarcas>
</modulos>
