=== Ajuan08/LMSGI_UD4/Concesionario/Caso Real/Mercedes.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT Mercedes (modelos)>
<!ATTLIST Mercedes
  xmlns CDATA #FIXED ''>

<!ELEMENT modelos (EQS,AMG,Clase)>
<!ATTLIST modelos
  xmlns CDATA #FIXED ''>

<!ELEMENT EQS (codIdentificacion,modelo,matricula,potencia,plazas,
               precio)>
<!ATTLIST EQS
  xmlns CDATA #FIXED ''>

<!ELEMENT AMG (codIdentificacion,modelo,matricula,potencia,plazas,
               precio)>
<!ATTLIST AMG
  xmlns CDATA #FIXED ''>

<!ELEMENT Clase (codIdentificacion,modelo,matricula,potencia,plazas,
                 precio)>
<!ATTLIST Clase
  xmlns CDATA #FIXED ''>

<!ELEMENT codIdentificacion (#PCDATA)>
<!ATTLIST codIdentificacion
  xmlns CDATA #FIXED ''>

<!ELEMENT modelo (#PCDATA)>
<!ATTLIST modelo
  xmlns CDATA #FIXED ''>

<!ELEMENT matricula (#PCDATA)>
<!ATTLIST matricula
  xmlns CDATA #FIXED ''>

<!ELEMENT potencia (#PCDATA)>
<!ATTLIST potencia
  xmlns CDATA #FIXED ''>

<!ELEMENT plazas (#PCDATA)>
<!ATTLIST plazas
  xmlns CDATA #FIXED ''>

<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio
  xmlns CDATA #FIXED ''>

=== Ajuan08/LMSGI_UD4/Concesionario/Caso Real/Mercedes.xml
<?xml version="1.0" encoding="IS0-8859-1"?>
<!DOCTYPE Mercedes SYSTEM "Mercedes.dtd">
<Mercedes>
    <modelos>
        <EQS>
            <codIdentificacion>0011</codIdentificacion>
            <modelo>Sport</modelo>
            <matricula>2402DYG</matricula>
            <potencia>400</potencia>
            <plazas>5</plazas>
            <precio>100.000€</precio>   
        </EQS>
        <AMG>
            <codIdentificacion>1122</codIdentificacion>
            <modelo>Competition</modelo>
            <matricula>2200GYT</matricula>
            <potencia>300</potencia>
            <plazas>2</plazas>
            <precio>50.000€</precio> 
        </AMG>
        <Clase>
            <codIdentificacion>3333</codIdentificacion>
            <modelo>Coupe</modelo>
            <matricula>6677DES</matricula>
            <potencia>200</potencia>
            <plazas>2</plazas>
            <precio>20.000€</precio> 
        </Clase>
    </modelos> 
</Mercedes>
