=== Ajuan08/LMSGI_UD4/Clientes/Caso Real/PcStore.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT PcStore (Tienda1,Tienda2)>
<!ATTLIST PcStore
  xmlns CDATA #FIXED ''>

<!ELEMENT Tienda1 (Madrid)+>
<!ATTLIST Tienda1
  xmlns CDATA #FIXED ''>

<!ELEMENT Tienda2 (Jerez)+>
<!ATTLIST Tienda2
  xmlns CDATA #FIXED ''>

<!ELEMENT Madrid (cliente1,CodPostal,fecha,descripcion)>
<!ATTLIST Madrid
  xmlns CDATA #FIXED ''>

<!ELEMENT Jerez (cliente1,CodPostal,fecha,descripcion)>
<!ATTLIST Jerez
  xmlns CDATA #FIXED ''>

<!ELEMENT cliente1 (nombre,telefono,email)>
<!ATTLIST cliente1
  xmlns CDATA #FIXED ''>

<!ELEMENT nombre (#PCDATA)>
<!ATTLIST nombre
  xmlns CDATA #FIXED ''>

<!ELEMENT telefono (#PCDATA)>
<!ATTLIST telefono
  xmlns CDATA #FIXED ''>

<!ELEMENT email (#PCDATA)>
<!ATTLIST email
  xmlns CDATA #FIXED ''>

<!ELEMENT CodPostal (#PCDATA)>
<!ATTLIST CodPostal
  xmlns CDATA #FIXED ''>

<!ELEMENT fecha (#PCDATA)>
<!ATTLIST fecha
  xmlns CDATA #FIXED ''>

<!ELEMENT descripcion (#PCDATA)>
<!ATTLIST descripcion
  xmlns CDATA #FIXED ''>

=== Ajuan08/LMSGI_UD4/Clientes/Caso Real/PcStore.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE PcStore SYSTEM "PcStore.dtd">
<PcStore>
    <Tienda1>
        <Madrid>
            <cliente1>
                <nombre>Juan</nombre>
                <telefono>620577325</telefono>
                <email>juanito@gmail.com</email>
            </cliente1>
            <CodPostal>11406</CodPostal>
            <fecha>Marzo 2016</fecha>
            <descripcion>Cliente muy habitual</descripcion>
        </Madrid>
       <Madrid>
            <cliente1>
                <nombre>Sergio</nombre>
                <telefono>772299661</telefono>
                <email>sergi@gmail.com</email>
            </cliente1>
            <CodPostal>11600</CodPostal>
            <fecha>Enero 2019</fecha>
            <descripcion>Cliente habitual</descripcion>
        </Madrid>
    </Tienda1>
    <Tienda2>
        <Jerez>
            <cliente1>
                <nombre>Alberto</nombre>
                <telefono>009988776</telefono>
                <email>alberto@gmail.com</email>
            </cliente1>
            <CodPostal>11406</CodPostal>
            <fecha>Junio 2014</fecha>
            <descripcion>Cliente desagradable</descripcion>
        </Jerez>
       <Jerez>
            <cliente1>
                <nombre>Airam</nombre>
                <telefono>338811526</telefono>
                <email>airam00@gmail.com</email>
            </cliente1>
            <CodPostal>11401</CodPostal>
            <fecha>Febrero 2022</fecha>
            <descripcion>Cliente nuevo</descripcion>
        </Jerez>
    </Tienda2>
</PcStore>
