=== Ajuan08/LMSGI_UD4/Modulos CFGS/Caso Real/IES_LOS_REMEDIOS.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT IES_LOS_REMEDIOS (Asignaturas)+>
<!ATTLIST IES_LOS_REMEDIOS
  xmlns CDATA #FIXED ''>

<!ELEMENT Asignaturas (LenguajeMarcas|programacion)>
<!ATTLIST Asignaturas
  xmlns CDATA #FIXED ''>

<!ELEMENT LenguajeMarcas (Contenidos)>
<!ATTLIST LenguajeMarcas
  xmlns CDATA #FIXED ''>

<!ELEMENT programacion (Contenidos)>
<!ATTLIST programacion
  xmlns CDATA #FIXED ''>

<!ELEMENT Contenidos (Tema1,Tema2,Tema3)>
<!ATTLIST Contenidos
  xmlns CDATA #FIXED ''>

<!ELEMENT Tema1 (lenguaje,tipo,duracion,descripcion,nombre_profesor)>
<!ATTLIST Tema1
  xmlns CDATA #FIXED ''>

<!ELEMENT Tema2 (lenguaje,tipo,duracion,descripcion,nombre_profesor)>
<!ATTLIST Tema2
  xmlns CDATA #FIXED ''>

<!ELEMENT Tema3 (lenguaje,tipo,duracion,descripcion,nombre_profesor)>
<!ATTLIST Tema3
  xmlns CDATA #FIXED ''>

<!ELEMENT lenguaje (#PCDATA)>
<!ATTLIST lenguaje
  xmlns CDATA #FIXED ''>

<!ELEMENT tipo (#PCDATA)>
<!ATTLIST tipo
  xmlns CDATA #FIXED ''>

<!ELEMENT duracion (#PCDATA)>
<!ATTLIST duracion
  xmlns CDATA #FIXED ''>

<!ELEMENT descripcion (#PCDATA)>
<!ATTLIST descripcion
  xmlns CDATA #FIXED ''>

<!ELEMENT nombre_profesor (#PCDATA)>
<!ATTLIST nombre_profesor
  xmlns CDATA #FIXED ''>

=== Ajuan08/LMSGI_UD4/Modulos CFGS/Caso Real/IES_LOS_REMEDIOS.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE IES_LOS_REMEDIOS SYSTEM "IES_LOS_REMEDIOS.dtd">
<IES_LOS_REMEDIOS>
    <Asignaturas>
        <programacion>
            <Contenidos>
                <Tema1>
                    <lenguaje>JAVA</lenguaje>
                    <tipo>Practico</tipo>
                    <duracion>3 meses</duracion>
                    <descripcion>Dificultad alta</descripcion>
                    <nombre_profesor>Javier</nombre_profesor>
                </Tema1>
                <Tema2>
                    <lenguaje>PHYTON</lenguaje>
                    <tipo>Practico</tipo>
                    <duracion>2 meses</duracion>
                    <descripcion>Dificultad facil</descripcion>
                    <nombre_profesor>Javier</nombre_profesor>
                </Tema2>
                <Tema3>
                    <lenguaje>C++</lenguaje>
                    <tipo>Practico</tipo>
                    <duracion>4 meses</duracion>
                    <descripcion>Dificultad media</descripcion>
                    <nombre_profesor>Javier</nombre_profesor>
                </Tema3>
            </Contenidos>
        </programacion>
    </Asignaturas>
    <Asignaturas>
        <LenguajeMarcas>
            <Contenidos>
                <Tema1>
                    <lenguaje>XML</lenguaje>
                    <tipo>Practico</tipo>
                    <duracion>2 meses</duracion>
                    <descripcion>Dificultad media</descripcion>
                    <nombre_profesor>Ana</nombre_profesor>
                </Tema1>
                <Tema2>
                    <lenguaje>HTML</lenguaje>
                    <tipo>Teorico</tipo>
                    <duracion>4 meses</duracion>
                    <descripcion>Dificultad facil</descripcion>
                    <nombre_profesor>Ana</nombre_profesor>
                </Tema2>
                <Tema3>
                    <lenguaje>CSS</lenguaje>
                    <tipo>Teorico</tipo>
                    <duracion>3 meses</duracion>
                    <descripcion>Dificultad media</descripcion>
                    <nombre_profesor>Ana</nombre_profesor>
                </Tema3>
            </Contenidos>
        </LenguajeMarcas>
    </Asignaturas>
</IES_LOS_REMEDIOS>
